# Generated by Django 3.0.7 on 2020-09-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20, verbose_name='userId')),
                ('sex', models.CharField(default='male', max_length=20, verbose_name='gender')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
            ],
            options={
                'verbose_name': 'user list',
                'verbose_name_plural': 'user list',
            },
        ),
    ]
